# Generated by Django 5.0.7 on 2024-07-18 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('book_services', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_set', to='user.customer'),
        ),
        migrations.AddField(
            model_name='popularity',
            name='id_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='user.customer'),
        ),
    ]
