# Generated by Django 5.0.7 on 2024-07-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_services', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularity',
            old_name='id_book',
            new_name='book',
        ),
    ]
