# Generated by Django 5.0.7 on 2024-07-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_services', '0003_rename_id_book_popularity_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='id_book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='id_customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='id_book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='id_customer',
            new_name='customer',
        ),
    ]
