# Generated by Django 5.0.7 on 2024-07-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_services', '0004_rename_id_book_borrow_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
