# Generated by Django 5.0.6 on 2024-08-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fines',
            field=models.ManyToManyField(blank=True, related_name='customers_fines', to='fine.fine'),
        ),
    ]
