# Generated by Django 5.0.6 on 2024-08-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_book_status_book_isbn_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
    ]
